export const API_CONSTANTS: any = {
    vendorLogin: 'Account/AthenticateVendor',
    login: 'user/Authenticate',
    menuList: 'Account/GetMenuList',
    refreshToken: 'user/Refresh',
    GetDashboardData: 'Dashboard/GetDashboardData',
    getmapviewData: 'MapView/GetMapViewData',
    getmapview2data: 'MapView/GetMapView2Data',
    getShiftData: 'Shift/GetShiftStatus',
    getCANData: 'MapView/GetCANData',
    GetOutsheddingDashboardData: 'Dashboard/GetOutsheddingDashboardData',
    complaintData: 'Dashboard/GetComplaintDashboard',
    GetDepartmentList: 'ITMS/GetDepartmentList',
    GetVehicleBasedOnZone: 'ITMS/GetVehicleBasedOnZone',
    GetVehicleChasisNo: 'ITMS/GetVehicleChasisNo',
    GetComplaintCategory: 'ITMS/GetComplaintCategory',
    GetCloseComplaint: 'Complaint/GetCloseComplaint',
    PostComplaint: 'Complaint/PostComplaint',
    ShowComplaintTimeLine: 'Complaint/ShowComplaintTimeLine',
    ShowComplaintThreads: 'Complaint/ShowComplaintThreads',
    AddComplaintTimeLine: 'Complaint/AddComplaintTimeLine',
    GetOpenComplaint: 'Complaint/GetOpenComplaint',
    ShowComplaint: 'Complaint/ShowComplaint',
    GetSearchComplaintPartNo: 'Complaint/GetSearchComplaintPartNo',
    GetShiftForRoster: 'Roster/GetShiftForRoster',
    DeviceList: 'skyitmsapi/Registration/GetDeviceList',
    ViewRoster: 'Roster/ViewRoster',
    ViewRosterForAtt: 'Roster/ViewRosterForAtt',
    MarkAttDMS: 'Roster/MarkAttDMS',
    allTripStatus: 'Dashboard/GetDashboardTripStatus',
    operatorData: 'Complaint/GetOperatorList?UserID=75',
    emissionReport: 'LocationMap/GetCarbonReport',

    /** registartion module */
    Departmentadd: 'Registration/Add_Department',
    ZoneMasterList: 'Registration/GetZone',
    DeviceRegistration: 'Registration/PostDevice',
    GetDeviceRegistration: 'Registration/GetDeviceList',
    AccidentRegistration: 'Registration/PostAccident',
    AddBatteryMaker: 'Registration/AddBatteryMaker',
    UpdateBatteryMaker: 'Registration/UpdateBatteryMaker',
    AddDamageType: 'Registration/AddDamageType',
    DriverRegistration: 'Registration/AddDriverRegistration',
    UpdateDriverRegistration: 'Registration/AddDriverRegistration',
    routeList: 'Registration/GetRoutelist',
    batteryMaker: 'Registration/BatteryMakerList',
    damageList: 'Registration/GetDamagelist',
    roleList: 'Registration/GetRolelist',
    stateList: 'Registration/GetStatelist',
    idProof: 'Registration/GetIDProfflist',
    zoneList: 'Registration/GetZone',
    addZone: 'Registration/Add_Zone',
    updateZone: 'Registration/Update_Zone',
    department: 'Registration/GetDepartment',
    addRouteRegistration: 'Registration/PostRouteRegistration',
    routeListData: 'Registration/GetRoutelist',
    RcDetailsList: 'RcDetails/RcDetailsList',
    stopTypeList: 'LocationMap/GetStopList',
    districtList: 'LocationMap/GetDistrictMasterList',
    addLocation: 'LocationMap/Add_Location',
    driverList: 'Registration/GetDriverlist',
    vechileMasterList: 'Registration/GetVehicleMaster',
    addVehicle: 'Registration/AddVehicleMaster',
    tyrelinkingList: 'Tyre/GetTyreTyrelinking',
    addTyreMaster: 'Tyre/AddTyreMaster',
    addTyreLinking: 'Tyre/AddTyrelinking',
    addTyreNsd: 'Tyre/AddNSD',
    getNsdList: 'Tyre/GetTyreNSDLIST',
    familyList: 'Registration/GetFamilyGridLatest',
    healthList: 'Registration/GetHealthGridLatest',
    professionalList: 'Registration/GetProfessionalGridLatest',
    addFamily: 'Registration/AddFamily',
    addHealth: 'Registration/AddHealth',
    addProfessional: 'Registration/AddProfessional',
    addVehicleDoucment: 'Registration/AddDocument',
    vehicleDocumentList: 'Registration/Documentgrid',
    occupationList: 'Registration/GetOccupation',
    locationList: 'LocationMap/LocationList',
    accidentList: 'Registration/AccidentList',
    userAccess: 'Management/GetMenuListForUser',
    userList: 'ITMS/GetUserListForAccessPerm',
    addStop: 'Registration/AddStops',
    addRouteMaster: 'Registration/AddRouteMaster',
    routeMasterList: 'Registration/RouteMasterGrid',

    /** management module */
    changePassword: 'Account/ChangePassword',
    userRoleList: 'Registration/GetAddRoleList',
    addUserRole: 'Registration/AddRole',
    deviceList: 'Registration/GetDeviceList',
    subVehicleType: 'Registration/GetSubTypeVehicle',
    getRouteList: 'Registration/GetRouteBind',
    getshiftlist: 'AddRosterStaff/GetShift',
    staffAttendance: 'AddRosterStaff/AttendanceEmployeeList',
    GetDriverList: 'ITMS/GetDriverList',
    onOffRoadVehilce: 'ITMS/FillOnOffRoadVehicles',
    GetStateMasterList: 'LocationMap/GetStateMasterList',
    geoFenceList: 'GeoFence/GetStopeListLatLog',
    addRoster: 'Roster/AddRoster',
    viewRosterList: 'Roster/ViewRoster',
    complainType: 'TripComplaint/GetTypeComplaint',
    addGeneralComplain: 'TripComplaint/AddGeneralComplain',
    attendanceList: 'Attendance/GetAttandance',
    checkStatus: 'Registration/GetcheckStatus',
    addMarkManual: 'Attendance/AddMarkManual',
    getgeofencelist: 'GeoFence/GetGeoFenceList',
    breakdownList: 'BreakDownComplaint/GetBDCgridList',
    partName: 'BreakDownComplaint/GetPartName',
    attendanceRoleList: 'Registration/GetRolelist',
    addBreakdown: 'BreakDownComplaint/AddBreakDownComplaint',
    staffAttendanceList: 'AddRosterStaff/GetEmployeeAttendanceList',
    assignSelectedZone: 'Management/AssignSelectedZone',
    unAssignSelectedZone: 'Management/UnAssignSelectedZone',
    manageAlert: 'ITMS/GetAlertType',
    manageAlertAsigned: 'ITMS/GetAlertAssignedVehicleList',
    ShowAlertSettings: 'Management/ShowAlertSettings',
    RemoveAlertSettings: 'Management/RemoveAlertSettings',
    UpdateAlertSettings: 'Management/UpdateAlertSettings',
    GetContactDetailsForAlert: 'Management/GetContactDetailsForAlert',
    viewStaff: 'AddRosterStaff/GetStaffView',
    addStaff: 'AddRosterStaff/SaveStaffRoster',
    employeeList: 'AddRosterStaff/EmployeeList',
    UpdateLinkingZone: 'Management/UpdateLinkingZone',
    AddAlertSettings: 'Management/AddAlertSettings',
    checkInData: 'AddRosterStaff/AttendanceCheckInOut',
    saveCheckIn: 'AddRosterStaff/SaveAttendanceCheckInCheckout',
    adduserAccess: 'Management/AddUserAccess',
    alertMaster: 'Registration/AlertMaster',
    updateAlertMaster: 'Registration/UpdateAlertRemarks',
    moduleMenuList:'api/ScComman/GetModuleMenuList/{moduleId}',

    /** Tracking/GetTrackingHistory */

    getlistoftracking: 'Tracking/GetTrackingHistory',
    updateGeofence: 'GeoFence/AddGeoFence',

    // reportPart

    routeVoilationReport: 'Report/GetRouteVoilationReport',
    statusReport: 'Report/GetShiftStatusReport',
    stayReport: 'Report/GetStayReport',
    tripReport: 'Report/TripStatusReport',
    dutyChangeReport: 'Report/GetDutyReport',
    missBusStop: 'Report/MissStatusReport',
    geoFance: 'Report/GeoFenceReport',
    GetTrackingHistoryReplay: 'Tracking/GetTrackingHistoryReplay',
    dutyReport: 'Report/GetDutyReport',
    updateDutyReport: 'Report/UpdateDutyReport',
    LocationStatusReport: 'Report/LocationStatusReport',
    InfractionStatusReport: 'Report/InfractionStatusReport',
    breakdownReport: 'BreakDownComplaint/GetBDCgridReport',
    missStopDetail: 'Report/GetStopStatusofTrip',
    gpsWiseBilling: 'Report/GPSReportDate',
    overSpeedReport: 'Report/OverSpeedReport',
    driverDutyChangeReport: 'Report/DriverDutyChangeReport',
    routeSurveyDropDwon: 'Route/routemasterlist',
    routeSurveyList: 'route/routestopmasterlist',
    socChangeReport: 'Report/Get_stop_duration_report',
    carbonReport: 'LocationMap/GetCarbonReportDayWise',

    /** dashboard fleet status */
    dashboardfleetstatus: 'Dashboard/GetFleetStatusOnTrip',
    qualityinspection: 'Dashboard/GetQualityTestingReport',
    tracking: 'Tracking/GetTripDetailsByVehicleId',
    stopWiseData: 'PassengerComp/StopWiseVehicleDetails',
    totalpassenger: 'PassengerComp/PassengerComplTotalLatest',
    dutytracking: 'PassengerComp/DutyTraking',

    /**
     * stock inventory api start here
     */
    manufactureList: 'ProductMaster/GetManufacturerList',
    supplierList: 'ProductMaster/GetSupplierNameList',
    manufactureNameList: 'ProductMaster/GetManufactureringGrid',
    productList: 'ProductMaster/GetProductListLatest',
    contactList: 'api/Supplier/GetSupplierList',
    countryListData: 'api/ScComman/GetCountryList',
    stateListData: 'api/ScComman/GetStateList/{countryId}',
    cityListData: 'api/ScComman/GetDistrictList/{districtId}',
    addSupplier: 'api/Supplier/CreateSupplier',
    updateSupplier: 'api/Supplier/UpdateSupplier',
    deleteSupplier: 'api/Supplier/DeleteSupplier',
    updateSupplierAddress: 'api/Supplier/UpdateSupplierAddress',
    addSupplierAddress: 'api/Supplier/AddOtherAddress',
    addManufacture: 'ProductMaster/AddManufacturer',
    unitConversion: 'ProductMaster/GetUnitConversionList',
    subCateDrop: 'ProductMaster/GetSubCategoryDrop',
    addunitConversion: 'ProductMaster/AddConversionUnit',
    chargingList: 'Charging/ChargingDetailsList',
    jobCardList: 'Charging/listjobcards',
    addJob: 'Charging/AddjobCards',
    hsnDroplist: 'ProductMaster/GetHSNDropDown',
    addMenufatcure: 'ProductMaster/AddManufacturer',
    addProduct: 'api/Item/CreateItem',
    updateProduct: 'api/Item/UpdateItem',
    addCharging: 'Charging/AddCharging',
    vehicleBattery: 'Charging/VehicleBatteryStatus',
    getVendorDetails: 'Quotation/GetVendorDetails',
    categoryListById: 'ProductMaster/GetLatestCategoryList',

    /**
     * inventory api start here
     */

    poList: 'PurchaseOrder/GetPurchaseOrderList',
    barCodeList: 'PurchaseOrder/GetAutocompleteBarCode',
    productNameList: 'PurchaseOrder/GetAutocompleteProductList',
    detailsFromBarcode: 'PurchaseOrder/GetProductDetailByBarCode',
    mrnList: 'MRN/GetMRNList',
    mrnChildList: 'Quotation/GetMRNChildDetails',
    quotationMrn: 'Quotation/GetMRNlist',
    mrnListDetails: 'Quotation/GridMRNlistDetails',
    quotationVendor: 'Quotation/VendorList',
    mrnType: 'ITMS/GetMRNGenerateType',
    RFPGenerate: 'Quotation/RFPGenerate',
    RPFList: 'Quotation/RFPLISTTOTALAMOUNT',
    rfpChildList: 'Quotation/GetRFPChildDetails',
    mrnCreate: 'MRN/CreateMRN',
    editmrnDetails: 'MRN/GetMRNDetailsForEdit',
    QuotationBaseOnPOList: 'Quotation/QuotationBaseOnPOList',
    GetQuotationDetails: 'Quotation/GetQuotationDetails',
    GRNDetailsList: 'GRN/GetGRNDetailsList',
    CreatePurchageOrder: 'PurchaseOrder/CreatePurchageOrder',
    quotationNoDropdown: 'PurchaseOrder/QuotationDrop',
    poLIst: 'PurchaseOrder/POLISbyid',
    poListChild: 'PurchaseOrder/polistbyidchiold',
    createGrn: 'GRN/CreateGRN',
    undoProcess: 'Roster/UndoLastProcess',

    // jobcard api start here
    partDescription: 'Charging/GetPartDropDown',
    complaintType: 'Charging/GetComplaintDropDown',

    /**
     * create route on map
     */

    getStopData: 'Tracking/GetStopListByRoute',

    // supplychan master api here
    hsnList: 'api/HSN/HSNList',
    addHSN: 'api/HSN/CreateHSN',
    updateHsn: 'api/HSN/UpdateHSN',
    deleteHsn: 'api/HSN/DeleteHSN',
    unitList: 'api/Unit/UnitList',
    addUnit: 'api/Unit/CreateUnit',
    updateUnit: 'api/Unit/UpdateUnit',
    deleteUnit: 'api/Unit/DeleteUnit',
    brandList: 'api/Brand/BrandList',
    addBrand: 'api/Brand/CreateBrand',
    updateBrand: 'api/Brand/UpdateBrand',
    deleteBrand: 'api/Brand/DeleteBrand',
    categoryList: 'api/Category/CategoryList',
    addCategoryData: 'api/Category/CreateCategory',
    updateCategoryData: 'api/Category/UpdateCategory',
    deleteCategory: 'api/Category/DeleteCategory',
    subCategoryList: 'api/SubCategory/SubCategoryList',
    addSubCategory: 'api/SubCategory/CreateSubCategory',
    updateSubCategory: 'api/SubCategory/UpdateSubCategory',
    deleteSubategory: 'api/SubCategory/DeleteSubCategory',
    countryMasterList:'api/Location/CountryList',
    createCountry:'api/Location/CountryAdd',
    updateCountry:'api/Location/CountryEdit',
    deleteCountry:'api/Location/CountryDelete',
    stateMasterList:'api/Location/StateList',
    createState:'api/Location/StateAdd',
    updateState:'api/Location/StateEdit',
    deleteState:'api/Location/StateDelete',
    districtMasterList:'api/Location/DistrictList',
    createDistrict:'api/Location/DistrictAdd',
    updateDistrict:'api/Location/DistrictEdit',
    deleteDistrict:'api/Location/DistrictDelete',
    itemMappigList:'api/Supplier/SupplierItemMappingList',
    linkItemMapping:'api/Supplier/SupplierItemMapping',
    deLinkItemMapping:'api/Supplier/SupplierItemMappingDelink',
    supplierLogin:'api/Supplier/GenerateSupplierLogin',
    resetSupplierLogin:'api/Supplier/ResetSupplierLogin',
    levelList:'api/Level/LevelList',
    createLevel:'api/Level/CreateLevel',
    updateLevel:'api/Level/UpdateLevel',
    deleteLevel:'api/Level/DeleteLevel',
     locationListData:'api/WorkLocation/LocationList',
    createLocation:'api/WorkLocation/CreateLocation',
    updateLocation:'api/WorkLocation/ModifyLocation',
    deleteLocation:'api/WorkLocation/DeleteLocation',
    levelMappingList:'api/level/LevelMappingList',
    createLevelMapping:'api/level/CreateLevelMapping',
    updateLevelMapping:'api/level/UpdateLevelMapping',
    deleteLevelMapping:'api/level/DeleteLevelMapping',
    deptByRollList:'api/ScComman/GetDeptRoleList/{deptid}',
    rollListByemp:'api/ScComman/GetRoleEmployeeList/{roleid}',
    itemLocation:'api/ScComman/GetItemLocationList',
    locationMappingList:'api/WorkLocation/LocationMappingList',
    createLocationMapping:'api/WorkLocation/CreateLocationMapping',
    updateLocationMapping:'api/WorkLocation/UpdateLocationMapping',
    deleteLocationMapping:'api/WorkLocation/DeleteLocationMapping',
    sessionList:'api/VoucherSetup/VSessionList',
    createSession:'api/VoucherSetup/CreateVSession',
    updateSession:'api/VoucherSetup/UpdateVSession',
    activeInactiveSession:'api/VoucherSetup/ActiveVSession',
    voucherList:'api/VoucherSetup/VoucherSetupList',
    createVoucher:'api/VoucherSetup/CreateVoucher',
    updateVoucher:'api/VoucherSetup/UpdateVoucherSetup',
    
    /**
     * tyre part api 
     */
    tyreMasterList: 'Tyre/GetTyreMaster',
    tyreVendorList: 'Tyre/TyreSendVendorList',
    addRetreadVendor: 'Tyre/AddRetreadingTyreSendToVendor',
    recievedTyreList: 'Tyre/ReceivedTyreStockList',
    addStoreReceived: 'Tyre/AddStoreReceived',
    addDamageTyre: 'Tyre/AddDamageTyre',
    tyreNumberLIst: 'Tyre/GetTyreNo',
    tyreNoVehicleWise: 'Tyre/VehicleNoWise',
    damageTyreList: 'Tyre/DamageTyreGrid',
    linkingReportList: 'Tyre/TyreLinkingReport',

    /**
     * operational
     */

    addMarkAtt: 'Roster/MarkAttDMS',
    gpsStatusData: 'Roster/GetLastGPSStatus',
    obuStatusData: 'Roster/GetGPSOBUDetails?VehicleID=id',
    markShiftOn: 'Roster/MarkShiftOn',
    onOffRoadVehicle: 'ITMS/FillOnOffRoadVehicles',
    onOffRoadKms: 'Management/GetOnOffRoadKms',
    markOnRoad: 'Management/MarkOnRoad',
    markOffRoad: 'Management/MarkOffRoad',
    GetZoneAssignedVehicleList: 'ITMS/GetZoneAssignedVehicleList',
    markDepotOut: 'Roster/MarkDepotOut',
    markDepotIn: 'Roster/MarkAttDMS',
    MarkShiftOff: 'Roster/MarkShiftOff',
    breakdownReason: 'ITMS/GetBreakdownReason',
    rosterApplyChange: 'Roster/RosterApplyChange',

    /**
     * maintenance
     */
    batteryNoList: 'Battery/GetBatteryNoList',
    getLocation: 'Battery/GetLocation',
    addBatteryLinking: 'Battery/AddBatteryLinking',
    batteryMasterList: 'Battery/GetBatteryMasterList',
    addBatteryMaster: 'Battery/AddBatteryMaster',
    batteryLinkList: 'Battery/GetBatteryList',
    warrentyClaimist: 'Battery/GetWarrentyClaimList',
    warrentySendToVendor: 'Battery/AddSendVendor',
    warrentyClaimReceivedList: 'Battery/GetWarrentyClaimReceivedList',
    batteryChargeStatus: 'Battery/GetBatteryChargeStatus',
    batteryHealthList: 'Battery/GetBatHealthChekuplist',
    addBatteryHealthCheckup: 'Battery/AddBatteryHealthCheckup',
    batTeriminallist: 'Battery/GetBatTeriminallist',
    addBatteryTeriminal: 'Battery/AddBatteryTeriminal',
    warrentyReceivedAdd: 'Battery/WarrentyReceivedAdd',

    rfpList: 'Quotation/RFPLISTTOTALAMOUNT',
    CreateQuotation: 'Quotation/CreateQuotation',
    rpfChild: 'Quotation/RFPLISTBYIDCHILDDETAILS',

    vendorDashboard: 'Dashboard/GetVendorDashboard',
    deliveryChallan: "Quotation/ChallanGenerate",
    posDetailsList: "Quotation/POSGETDetails",
    totalVehicleRecord: 'Report/VehicleDetailsReport',
    punctureTyreReport: 'Tyre/TyreLinkingReport',

    // billing report api here

    billingReport: 'Report/BillingReportV1',
    odometerreport: 'Report/OdometerReportlatest',
    stopreportintervalwise: 'Report/StopReportIntervalWise',
    //charging station part api here
    distancereport: 'Report/DurDistTravelled',
    //driver wise trip report api here
    DriverWiseTripReport: 'Report/DriverWiseTripReport',
    //biilingreport 
    BillingReportDateWise: 'Report/BillingReportDateWise',

    totalDevice: 'getDeviceState',

    //in actual infraction report
    InfractionReport: 'Report/InfractionReport',
    missStopReason: 'Registration/MissStopReason27',
    getstoopagedata: 'Report/StoppageReport',

    // attendance api
    showAttendance: 'Attendancev2/AttendanceReport',

    //vehiclewise Shift
    vehicleshift: 'Report/GetVehicleShiftstatus',
    dailySummaryReport: 'Dashboard/GetDailySummaryReport',

    //charging report api
    // chargingReport:'Charging/ChargingSOCReport',
    chargingReport: 'Report/ShiftWiseVehicleSOCReport_v1',
    reportManualVsGPS: 'Report/BillingReportManualVsGPS',
    routeFance: 'Registration/CreateRouteFencing',
    vehicleList: 'Report/DriverBus',
    alertCall: 'Registration/AlertDashboards',
    fencingList: 'Registration/GetRouteFencingList',

    // workshop Module Api
    addInspection: 'WorkShop/PostInspectionMaster',
    getInspection: 'WorkShop/GetInspectionMaster',
    InspectionChild: 'workshop/Getjobcategoryoninspection',
    getServiceType: 'WorkShop/GetServiceTypeMaster',
    getPassInData: 'WorkShop/GetAllGatePasses',
    createGatePass: 'WorkShop/PostGatePass',
    MechanicData: 'WorkShop/GetMechanicList',
    createJob: 'WorkShop/CreateJobCard',
    jobCardData: 'WorkShop/GetJobCardList',
    jobCardChildData: 'WorkShop/GetJobCardJobDetails?RequestID=id',
    complaintReport: 'Report/GetComplaintReport',
    issueMaterial: 'WorkShop/PostMaterialIssue',
    productChild: 'WorkShop/GetMaterialIssued',
    addNewRoute: 'Registration/CreateRoute',
    updateRouteDetails: 'Registration/UpdateRoute',
    routeDetailsForEdit: 'Registration/GetRouteDetailsForEdit',
    allCanData: 'MapView/GetFleetStatusBasedOnCANData',
    chargingData: 'MapView/GetVehicleChargingStatus',
    deviceHealth: 'Report/GetDeviceHealthReport',
    dorReport: 'Report/DORReport',
    driverTripReport: 'TripComplaint/GetDriverTripInfo',
    moduleList: 'User/GetModuleList',
    menu: 'Management/GetModuleMenuList',
    addMenu: 'Management/AddMenuMaster',
    updateMenu: 'Management/EditMenuMaster',
    accessList: 'User/GetMenuAccessList',
    postMenuAccess: 'User/PostMenuAccess',
    operationStat: 'Route/GetCarbonData',

    // product master new api and dropdown
    itemList: 'api/Item/ItemList',
    deleteItem: 'api/Item/DeleteItem',
    categoryDropdown:'api/ScComman/GetCategoryList',
    subCategoryDropdown:'api/ScComman/GetSubCategoryList/{id}',
    unitDropdown:'api/ScComman/GetUnitList',
    hsnDropdown:'api/ScComman/GetHsnList',
    brandDropdown:'api/ScComman/GetBrandList',
    billingForDropdown:'api/ScComman/GetBillingForList',
    billingCategoryDropdown:'api/ScComman/GetBillingCategoryList',
};


export const chargingBaseUrl = 'https://platform.kazam.in/';

export const LAT = 20.29573;
export const LNG = 85.82476;

export const imgPath = 'http://103.89.45.88/skyitmsapi/Uploads/InfractionImg/'
